function pltopts = my_plotting_options_synthetic

color1 = [0 0.4470 0.7410];
color2 = [0.8500 0.3250 0.0980];
color3 = [0.9290 0.6940 0.1250];
color4 = [0.4940 0.1840 0.5560];
color5 = [0.4660 0.6740 0.1880];

pltopts.color = containers.Map({'blind_nonparametric','blind_parametric_LB_avg_UB','EM','genie','accelerated_EM','baseline_EM'},{color5,color3,color1,color2,color5,color4});
pltopts.linestyle = containers.Map({'blind_nonparametric','blind_parametric_LB_avg_UB','EM','genie'},{'-','--','-.',':'});
pltopts.mylinestyle2list = {'-','--','-.',':','-','--','-.'};
pltopts.marker = containers.Map({'blind_nonparametric','blind_parametric_LB_avg_UB','EM','genie','accelerated_EM','baseline_EM'},{'x','>','d','none','d','o'});

pltopts.display_name = containers.Map({'accelerated_EM','baseline_EM'},{'accelerated EM with $p^\textrm{init}','baseline EM with $p^\textrm{init}'});

pltopts.est_label_N0 = {'blind nonparametric estimate $\widehat{N}_0$',...
  'blind parametric estimate $\widehat{N}_0(\hat{p}(',...
  'expectation-maximization estimate $\widehat{N}_0^\textrm{EM}$',...
  'genie-aided estimate $\overline{N}_0$ (baseline)',...
  'reference $N_0$ (baseline)'};
pltopts.est_label_Es = {'blind nonparametric estimate $\widehat{E}_s$',...
  'blind parametric estimate $\widehat{E}_s(\hat{p}(',...
  'expectation-maximization estimate $\widehat{E}_s^\textrm{EM}$',...
  'genie-aided estimate $\overline{E}_s$ (baseline)',...
  'reference $E_s$ (baseline)'};
pltopts.est_label_SNR = {'blind nonparametric estimate $\widehat{\textit{SNR}}$',...
  'blind parametric estimate $\widehat{\textit{SNR}}(\hat{p}(',...
  'expectation-maximization estimate $\widehat{\textit{SNR}}{\>\!}^\textrm{EM}$',...
  'genie-aided estimate $\overline{\textit{SNR}}$ (baseline)',...
  'reference $\textit{SNR}$ (baseline)'};
pltopts.est_label_MSE = {'blind nonparametric estimate $\widehat{\textit{MSE}}$',...
  'blind parametric estimate $\widehat{\textit{MSE}}(\hat{p}(',...
  'expectation-maximization estimate $\widehat{\textit{MSE}}{\>\!}^\textrm{EM}$',...
  'genie-aided estimate $\overline{\textit{MSE}}$ (baseline)',...
  'reference $\textit{MSE}$ (baseline)'};

end